### PR TITLE
fix `--no-cache` support

### LINKED ISSUE #199: error with `--no-cache` in composer 1.9
This may or may not be an actual issue. But composer 1.9 now comes with a `--no-cache` global option which I tried to use for installing prestissimo in docker so that I don't have to call `composer clear-cache` afterwards. I understand the 2 are different but I thought perhaps prestissimo won't do anything yet when it's first installed (excuse my lack of understanding of how composer plugins work).

`composer global require --no-cache hirak/prestissimo -v` gives

```
/app # composer global require --no-cache hirak/prestissimo -v                                                                                                                                                                        Changed current directory to /tmp
Using version ^0.3.9 for hirak/prestissimo
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.000 seconds
Analyzed 75 packages to resolve dependencies
Analyzed 46 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals                                                                                                                                                                                  Installs: hirak/prestissimo:0.3.9
  - Installing hirak/prestissimo (0.3.9): Downloading (100%)
 Extracting archivePlugin installation failed, rolling back
  - Removing hirak/prestissimo (0.3.9)

Installation failed, deleting ./composer.json.                                                                                                                                                                                        

  [ErrorException]
  mkdir(): Not a directory  

Exception trace:                                                                                                                                                                                                                       () at /tmp/vendor/hirak/prestissimo/src/CopyRequest.php:103
Composer\Util\ErrorHandler::handle() at n/a:n/a                                                                                                                                                                                       mkdir() at /tmp/vendor/hirak/prestissimo/src/CopyRequest.php:103
Hirak\Prestissimo\CopyRequest->createDir() at /tmp/vendor/hirak/prestissimo/src/CopyRequest.php:89
Hirak\Prestissimo\CopyRequest->setDestination() at /tmp/vendor/hirak/prestissimo/src/CopyRequest.php:39
Hirak\Prestissimo\CopyRequest->__construct() at /tmp/vendor/hirak/prestissimo/src/ParallelizedComposerRepository.php:26
Hirak\Prestissimo\ParallelizedComposerRepository->preloadProviderListings() at /tmp/vendor/hirak/prestissimo/src/ParallelizedComposerRepository.php:39
Hirak\Prestissimo\ParallelizedComposerRepository->prefetch() at /tmp/vendor/hirak/prestissimo/src/Plugin.php:150
Hirak\Prestissimo\Plugin->prefetchComposerRepositories() at /tmp/vendor/hirak/prestissimo/src/Plugin.php:82
Hirak\Prestissimo\Plugin->activate() at phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php:237
Composer\Plugin\PluginManager->addPlugin() at phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php:206
Composer\Plugin\PluginManager->registerPackage() at phar:///usr/bin/composer/src/Composer/Installer/PluginInstaller.php:62
Composer\Installer\PluginInstaller->install() at phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:173
Composer\Installer\InstallationManager->install() at phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:160
Composer\Installer\InstallationManager->execute() at phar:///usr/bin/composer/src/Composer/Installer.php:597
Composer\Installer->doInstall() at phar:///usr/bin/composer/src/Composer/Installer.php:229
Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php:218
Composer\Command\RequireCommand->doUpdate() at phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php:175
Composer\Command\RequireCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:245
Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:835
Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:185
Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:267
Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:106
Composer\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Command/GlobalCommand.php:101
Composer\Command\GlobalCommand->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:835
Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:185
Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:267
Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:106
Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:61
require() at /usr/bin/composer:24
```

Works fine without the `--no-cache` option. Then trying to install any package with the `--no-cache` option produces the same error which kind of makes sense as prestissimo relies on a cache directory. I guess a more friendly behavior is to fall back to normal composer if cache is disabled. But it's not a biggie.

The question is whether the cache directory is a hard requirement for installing prestissimo for the first time?

### PR DESCRIPTION
**Pull request by IonBazan**
This change disables prestissimo when `--no-cache` flag is passed.
Regex is taken from https://github.com/composer/composer/blob/f154d5c09d69a6338d6a955bf51cc264d0448b3d/src/Composer/Cache.php#L62-L65

fixes #199

### CODE REVIEW

File: src/Plugin.php [hunk 1]
```diff
@@ -72,6 +72,12 @@ class_exists(__NAMESPACE__ . '\\' . $class);
         $this->config = $composer->getConfig();
         $this->package = $composer->getPackage();
 
+        $cacheDir = rtrim($this->config->get('cache-files-dir'), '\/');
+
+        if (preg_match('{(^|[\\\\/])(\$null|nul|NUL|/dev/null)([\\\\/]|$)}', $cacheDir)) {
```
Comment (kubawerlos) [inline src/Plugin.php]: Function `preg_match` returns false on error, so better compare the result to `1`.

Comment (edutrul) [reply src/Plugin.php:77]: This is working for me ^^

**Comment by IonBazan** [comment]
@kubawerlos Tests added :)
